name: Update Library Action

description: Update Library

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Update Library
      run: |
        echo $PORTO_CREDENTIALS_PROD
        python -m pip install --upgrade pip ; pip3 install pylint pytest pytest-mock faker coverage pytest-cov keyring keyrings.google-artifactregistry-auth
        echo $PORTO_CREDENTIALS_PROD|gcloud auth activate-service-account --key-file=-
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      shell: bash
